services:
  - type: web
    name: Yegnafit
    env: python
    buildCommand: "apt-get update && apt-get install -y tesseract-ocr libtesseract-dev && pip install -r requirements.txt"
    startCommand: "uvicorn bot:app --host 0.0.0.0 --port $PORT"
